# Generated by Django 4.2.6 on 2023-10-28 13:01

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_alter_book_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=book.models.create_custom_image_file_path,
            ),
        ),
    ]
